export const ETHIOPIA_REGIONS = [
	"Addis Ababa",
	"Afar",
	"Amhara",
	"Benishangul-Gumuz",
	"Central Ethiopia",
	"Dire Dawa",
	"Gambela",
	"Harari",
	"Oromia",
	"Sidama",
	"Somali",
	"South Ethiopia",
	"South West Ethiopia Peoples",
	"Tigray",
] as const;
